application: msgboardy
version: 1
runtime: go
api_version: go1

handlers:
- url: /(pages).*
  script: _go_app
- url: /
  static_files: frontend/admin/index.html
  upload: frontend/admin/index.html
- url: /(.+)
  static_files: frontend/admin/\1
  upload: frontend/admin/.*
