application: msgboardy
version: 1
runtime: go
api_version: go1

handlers:
- url: /(api).*
  script: _go_app
- url: /
  script: _go_app
- url: /admin/
  static_files: frontend/admin/index.html
  upload: frontend/admin/index.html
- url: /display/
  static_files: frontend/display/index.html
  upload: frontend/display/index.html
- url: /(.+)
  static_files: frontend/\1
  upload: frontend/.*
